services:
  bayesnet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bayesnet-app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python bayesnet_v3/inference.py
    #command: python bayesnet_v3/likelihood.py
